CREATE TABLE user_profile11 (
user_id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
hourly_rate DECIMAL(5, 2),
hire_rate DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
device_os VARCHAR(100) NOT NULL DEFAULT 'Android'
);
